version: '3.4'

services:
  etcd_master:
    image: 'bitnami/etcd:3.4.3'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_master:2379
    ports:
      - "2379:2379"
      - "2380:2380"
