version: "3.4"

services:
  etcd_master:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_master:2379
    ports:
      - 2379:2379
  foo1:
    image: alpine:3.2
    entrypoint: ["/app/main"]
    volumes:
      - ./build/bin/foo:/app/main:ro
    ports:
      - 50001:50000
  foo2:
    image: alpine:3.2
    entrypoint: ["/app/main"]
    volumes:
      - ./build/bin/foo:/app/main:ro
    ports:
      - 50002:50000
  foo3:
    image: alpine:3.2
    entrypoint: ["/app/main"]
    volumes:
      - ./build/bin/foo:/app/main:ro
    ports:
      - 50003:50000
