version: "3.4"

services:
  etcd_master:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd_master:2379
    ports:
      - 2379:2379
  foo1:
    image: alpine:3.2
    entrypoint: ["/app/main","--registry_address","etcd_master:2379"]
    volumes:
      - ./build/bin/foo:/app/main:ro
    links:
      - etcd_master
    depends_on:
      - etcd_master
  foo2:
    image: alpine:3.2
    entrypoint: ["/app/main","--registry_address","etcd_master:2379"]
    volumes:
      - ./build/bin/foo:/app/main:ro
    links:
      - etcd_master
    depends_on:
      - etcd_master
  foo3:
    image: alpine:3.2
    entrypoint: ["/app/main","--registry_address","etcd_master:2379"]
    volumes:
      - ./build/bin/foo:/app/main:ro
    links:
      - etcd_master
    depends_on:
      - etcd_master
  client:
    image: alpine:3.2
    entrypoint: ["/app/main","--registry_address","etcd_master:2379"]
    volumes:
      - ./build/bin/cli:/app/main:ro
    links:
      - etcd_master
    depends_on:
      - etcd_master
