// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/method_option.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OptionBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//認証不要
	IgnoreTokenVerify bool `protobuf:"varint,1,opt,name=ignore_token_verify,json=ignoreTokenVerify,proto3" json:"ignore_token_verify,omitempty"`
	//リクエスト内容をログに出力しない
	IgnoreLoggerPayload bool `protobuf:"varint,2,opt,name=ignore_logger_payload,json=ignoreLoggerPayload,proto3" json:"ignore_logger_payload,omitempty"`
}

func (x *OptionBase) Reset() {
	*x = OptionBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_method_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionBase) ProtoMessage() {}

func (x *OptionBase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_method_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionBase.ProtoReflect.Descriptor instead.
func (*OptionBase) Descriptor() ([]byte, []int) {
	return file_proto_method_option_proto_rawDescGZIP(), []int{0}
}

func (x *OptionBase) GetIgnoreTokenVerify() bool {
	if x != nil {
		return x.IgnoreTokenVerify
	}
	return false
}

func (x *OptionBase) GetIgnoreLoggerPayload() bool {
	if x != nil {
		return x.IgnoreLoggerPayload
	}
	return false
}

var file_proto_method_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OptionBase)(nil),
		Field:         50001,
		Name:          "pbbase.option_base",
		Tag:           "bytes,50001,opt,name=option_base",
		Filename:      "proto/method_option.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional pbbase.OptionBase option_base = 50001;
	E_OptionBase = &file_proto_method_option_proto_extTypes[0]
)

var File_proto_method_option_proto protoreflect.FileDescriptor

var file_proto_method_option_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x62,
	0x61, 0x73, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x0a, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x61, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x67, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x13, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x55, 0x0a, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x0a, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x42, 0x22,
	0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6d, 0x7a,
	0x33, 0x33, 0x31, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_method_option_proto_rawDescOnce sync.Once
	file_proto_method_option_proto_rawDescData = file_proto_method_option_proto_rawDesc
)

func file_proto_method_option_proto_rawDescGZIP() []byte {
	file_proto_method_option_proto_rawDescOnce.Do(func() {
		file_proto_method_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_method_option_proto_rawDescData)
	})
	return file_proto_method_option_proto_rawDescData
}

var file_proto_method_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_method_option_proto_goTypes = []interface{}{
	(*OptionBase)(nil),                 // 0: pbbase.OptionBase
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_proto_method_option_proto_depIdxs = []int32{
	1, // 0: pbbase.option_base:extendee -> google.protobuf.MethodOptions
	0, // 1: pbbase.option_base:type_name -> pbbase.OptionBase
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_method_option_proto_init() }
func file_proto_method_option_proto_init() {
	if File_proto_method_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_method_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_method_option_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_method_option_proto_goTypes,
		DependencyIndexes: file_proto_method_option_proto_depIdxs,
		MessageInfos:      file_proto_method_option_proto_msgTypes,
		ExtensionInfos:    file_proto_method_option_proto_extTypes,
	}.Build()
	File_proto_method_option_proto = out.File
	file_proto_method_option_proto_rawDesc = nil
	file_proto_method_option_proto_goTypes = nil
	file_proto_method_option_proto_depIdxs = nil
}
