// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/foo_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	pbcomm "github.com/gofc/grpc-micro/proto/v1/pbcomm"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/v1/foo_service.proto", fileDescriptor_f03c0d7acb171f0c) }

var fileDescriptor_f03c0d7acb171f0c = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x33, 0xd4, 0x4f, 0xcb, 0xcf, 0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0xd5, 0x03, 0x0b, 0x0a, 0x31, 0x15, 0x24, 0x49, 0xc9, 0xc1, 0xe5, 0x0b, 0x92, 0x92, 0xf3, 0x73,
	0x73, 0xf5, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x8b, 0x21, 0x6a, 0x8c, 0x5c, 0xb8, 0xb8,
	0xdc, 0xf2, 0xf3, 0x83, 0x21, 0xfa, 0x84, 0xcc, 0xb8, 0x58, 0x3d, 0x52, 0x73, 0x72, 0xf2, 0x85,
	0x44, 0xf4, 0x20, 0xca, 0xf5, 0xc0, 0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x29, 0x51,
	0x34, 0xd1, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x06, 0x27, 0xd5, 0x28, 0xe5, 0xf4, 0xcc,
	0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xf4, 0xfc, 0xb4, 0x64, 0xfd, 0xf4, 0xa2,
	0x82, 0x64, 0xdd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0x7d, 0x88, 0x13, 0x0a, 0x92, 0x92, 0xd8, 0xc0,
	0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x1f, 0x5a, 0x9e, 0xb5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FooServiceClient is the client API for FooService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FooServiceClient interface {
	Hello(ctx context.Context, in *pbcomm.HelloRequest, opts ...grpc.CallOption) (*pbcomm.HelloResponse, error)
}

type fooServiceClient struct {
	cc *grpc.ClientConn
}

func NewFooServiceClient(cc *grpc.ClientConn) FooServiceClient {
	return &fooServiceClient{cc}
}

func (c *fooServiceClient) Hello(ctx context.Context, in *pbcomm.HelloRequest, opts ...grpc.CallOption) (*pbcomm.HelloResponse, error) {
	out := new(pbcomm.HelloResponse)
	err := c.cc.Invoke(ctx, "/pb.FooService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooServiceServer is the server API for FooService service.
type FooServiceServer interface {
	Hello(context.Context, *pbcomm.HelloRequest) (*pbcomm.HelloResponse, error)
}

// UnimplementedFooServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFooServiceServer struct {
}

func (*UnimplementedFooServiceServer) Hello(ctx context.Context, req *pbcomm.HelloRequest) (*pbcomm.HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterFooServiceServer(s *grpc.Server, srv FooServiceServer) {
	s.RegisterService(&_FooService_serviceDesc, srv)
}

func _FooService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pbcomm.HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FooService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).Hello(ctx, req.(*pbcomm.HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FooService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FooService",
	HandlerType: (*FooServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _FooService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/foo_service.proto",
}
